[package]
name = "cargo-edit-locally"
version = "0.1.3"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["subcommand"]
repository = "https://github.com/alexcrichton/cargo-edit-locally"
description = """
A Cargo subcommand to edit dependencies locally via `[replace]`
"""

[dependencies]
cargo = "0.35"
curl = "0.4"
docopt = "1.1"
env_logger = { version = "0.6", default-features = false }
failure = "0.1"
git2 = "0.8"
pathdiff = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5"
openssl = { version = '0.10.20', optional = true }

[features]
vendored-openssl = ['openssl/vendored']
