[package]
name = "cargo-edit-locally"
version = "0.1.3"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["subcommand"]
repository = "https://github.com/alexcrichton/cargo-edit-locally"
description = """
A Cargo subcommand to edit dependencies locally via `[replace]`
"""

[dependencies]
cargo = "0.22"
curl = "0.4"
env_logger = { version = "0.4", default-features = false }
git2 = "0.7"
pathdiff = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
